app = "my-v2ray"

[build]
  image = ""

[env]

[[services]]
  internal_port = 10085
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    timeout = "2s"
    restart_limit = 0
